site_name: pystepdowner
theme:
  name: material
  palette:
    primary: teal
    accent: teal
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences
exclude_docs:
  - includes/*
  - docs_src/*
nav:
  - Main: index.md
  - Cases: cases.md
